### ISSUE TITLE
Next battle buttons don't work on mobile

### ISSUE THREAD

**Issue by artfoundry** [scottschiller/ArmorAlley#10]
The next battle button on the envelope that appears after completing a battle doesn't do anything when tapped aside from becoming highlighted. Played on iphone 13 Max Pro running 16.6.1.

**Comment by scottschiller** [comment]
D'oh! 😅 Thanks for the report. I _just_ added this yesterday and I had a feeling about mobile, but thought _nah, it should work_. 😂 
This should now be fixed up. The event was being swallowed by touch handlers.
