### ISSUE TITLE
Typos in Options panel

### ISSUE THREAD

**Issue by artfoundry** [scottschiller/ArmorAlley#11]
Missing 'y' in 'Stupidity' (heh heh unless it's supposed to be missing to show the stupidity...) and in 'Gameplay'
<img width="338" alt="Screenshot 2023-10-12 at 8 49 44 PM" src="https://github.com/scottschiller/ArmorAlley/assets/4854419/2da5ece3-a1e1-441b-a428-ecbc3fb23c5a">

Quote showing instead of 'x' in 'External'
<img width="196" alt="Screenshot 2023-10-12 at 8 49 51 PM" src="https://github.com/scottschiller/ArmorAlley/assets/4854419/9cd5dfdd-35a3-435d-b753-8e4deeba3c18">

**Comment by scottschiller** [comment]
This is a weird one; it's almost like the font has been corrupted. What browser and OS are you seeing this on? I haven't been able to repro, yet.

**Comment by artfoundry** [comment]
Ok, yeah this is weird - the problem is only in the rendering - in the dev tool, the text is correct.  And this is on Chrome 117.0.5938.149 on MacOS Ventura 13.5.1.  Also occurs on Firefox 118.0.2.  On Safari 16.6 though, it looks fine.

**Comment by scottschiller** [comment]
Bizarre! I'm on Sonoma 14.1, and have yet to see this in Firefox, Chrome or Safari.
Perhaps I should drop Chicago from the font list, and presume the look-alike `FA Sysfont C` webfont I've got for that will do the trick.

**Comment by artfoundry** [comment]
Maybe they fixed the issue in Sonoma? Seems like it would be a browser issue instead of OS, but 🤷‍♂️

**Comment by scottschiller** [comment]
It's interesting you saw it in Chrome and Firefox, but not Safari. Either way, I just pushed a change to drop chicago from the CSS. (You might have to shift + reload to get the latest assets, for today.)

Hopefully it fixes the issue, and still looks good. I hope I don't have to troubleshoot misplaced or missing glyphs - that's just strange. 🥴

**Comment by artfoundry** [comment]
Yeah, fixed now in both browsers.  The Sysfont one is a bit smaller, so might want to increase the size a bit if you care about keeping it the same size as it was before.

**Comment by scottschiller** [comment]
Thanks for confirming. It seems I actually don't have the Chicago font on this system, and so perhaps that's why I've never seen the issue; I'll check. I like the current size based on the webfont I originally specified.

Pulling the official Chicago font file from a System 7 install, it doesn't seem to work nor make a difference in rendering on my end. "Uncle," I say! 😆 For now, I'm calling this resolved by avoiding use of `Chicago` in the font-family list.
