### ISSUE TITLE
Game isn't starting on Chrome

### ISSUE THREAD

**Issue by artfoundry** [scottschiller/ArmorAlley#15]
Getting console errors when trying to start a game using Chrome (errors not occuring and game runs fine in Safari).  This is for Chrome ver. 120.0.6099.234 on OS 14.2.1.
Game level, difficulty, and B+B options don't seem to affect whether the errors occur.
Game fails to start properly and errors occur after hitting Start - there's the sound of the helicopter getting hit by a bullet, an expolosion in the upper left corner (assuming it's the helicopter), and sometimes a parachuter appears.  The title screen usually doesn't disappear (though does sometimes), enemies don't appear, and controls are nonfunctional.

<img width="1525" alt="Screenshot 2024-01-20 at 6 46 48 PM" src="https://github.com/scottschiller/ArmorAlley/assets/4854419/c3075bf1-e6cb-446c-a995-98b40dba000e">

**Comment by artfoundry** [comment]
Ok this is really weird.  Now I can't even get the title screen.  I was testing out the other issue I just entered (about the Options dialog), and now all I get is the radar, ground line, and B+B's voices talking about a menu being open (but the options dialog doesn't appear).  Getting slightly different console errors too. Reloading the page and going back to [armor alley url](https://armor-alley.net/) and clicking Start doesn't make any difference.  I can try deleting my cookies/local storage, but not sure what's saved there or which ones to delete - I'm assuming just options and last played level settings are stored?

<img width="1533" alt="Screenshot 2024-01-20 at 7 20 18 PM" src="https://github.com/scottschiller/ArmorAlley/assets/4854419/8fe67c20-98fd-4c5f-8fc3-e3386a8063e3">

**Comment by artfoundry** [comment]
I've now reproduced in Firefox the same issue as my above comment, but not with the same steps. Game started fine, but I discovered a new issue with FF (which I just reported).  I was trying to figure out how to fix it (disable Quickfind or disable using Z to open Quickfind), but was unable to. I noticed the options dialog in FF didn't display the keyboard controls, so I tried reloading the page to start over (to see if the keyboard controls would show up in options when it was opened from the title screen), and that's when the page loaded like in my above comment.

**Comment by scottschiller** [comment]
Ack! Thanks. I have not been able to repro this, yet. I've pushed a quick change which I think will address the undefined visibility thing - that's from a refactor I've done to render the radar on `<canvas>`. Maybe there's an async render / loading issue that's snuck in, somewhere. You may need to do a shift + reload, or clear cache, to get the latest for now.

**Comment by scottschiller** [comment]
I'm working on a large refactor and pushing most UI and rendering to canvas, but I haven't pushed the majority of that work yet. If you want to try the "2024 beta" link and see if that works any differently, that's here. https://play.armor-alley.net/temp/2024-beta/

**Comment by artfoundry** [comment]
Looks like the change you made fixed both this issue and the Options issue 👍

**Comment by scottschiller** [comment]
Thanks for confirming, glad to have that resolved. 😅
