### ISSUE TITLE
Opening and closing Options dialog sometimes causes page reload

### ISSUE THREAD

**Issue by artfoundry** [scottschiller/ArmorAlley#16]
If you open the Options, don't change anything or change some options, and click OK, the page reloads.  This happens on the title screen or in game.  It seems inconsistent which options WON'T cause the reload - it's very odd.  Also, if the page reloads, the options you changed before the reload are sometimes saved, but not always.  Issue also occurs if the network dialog is opened (which I realize is just an altered version of the options dialog).

**Comment by artfoundry** [comment]
It does seem like the more you play with it the worse it gets - in Safari (unable to test in Chrome now - see my comment in my other issue about game not starting), changing any option and closing the dialog is now causing reload.

**Comment by scottschiller** [comment]
Thanks for the report, something definitely sounds off. I haven't been able to reproduce any of this, yet.

If you open the network modal, that one will reload the page if you "cancel" from there as it exists only to start a network game from the splash screen.

If you open the regular options modal 🛠️ that shouldn't cause a reload.

When the screen is below 900px wide, the options and network are shown as one button to save space. You have to click "network setup" from that modal, and then you'll get the network-specific modal in that case which causes the reload.

**Comment by artfoundry** [comment]
Looks like the change you made for the Chrome freeze issue fixed both this issue and that one 🦜🦜🪨

**Comment by scottschiller** [comment]
Ah, good! Thanks. I realized I may not have pushed some image asset changes and that might have been related, too.
