### ISSUE TITLE
Clicking does not change the direction of the helicopter

### ISSUE THREAD

**Issue by supercobra** [scottschiller/ArmorAlley#3]
After some time playing, the helicopter does not change direction by clicking.

**Comment by supercobra** [comment]
It was on safari playing in full screen mode.

**Comment by scottschiller** [comment]
Thank you for the detail, I'm hoping to get a consistent repro and a fix for this one. I made a change related to auto-rotate recently for mobile, but that should not have affected desktop. That said, two recent reports suggests _something_ has happened. 😅

**Comment by scottschiller** [comment]
@supercobra and @whoisterencelee: I finally hit this bug in Safari! The bottom part of the game UI with the queue and `options | exit` links was overlapping some of the battlefield area and capturing clicks. This was likely a regression caused in fixing a long-standing text rendering issue specific to Safari.

It's illustrated here with the green border. Clicks were being "swallowed" within that area.
![Armor Alley - bottom UI overlay](https://github.com/scottschiller/ArmorAlley/assets/174437/c421ba13-ee05-4fa5-8919-869417c3925f)
While flying, clicking within that area would have no effect. Higher up, clicking would rotate the helicopter as expected.

Side note: The game should be less blurry now in Safari at full-screen, I finally fixed a long-standing transform / scale issue affecting text rendering. Shenanigans were involved, but it works. ;) ec66d3ee13853d5a7e1f5e14f9e570739988089d

Let me know if you continue to see this or any click issues after today, and maybe with a shift + reload to ensure you've got the latest code.

**Comment by supercobra** [comment]
The 'click to U-turn' works well now on Safari.

**Comment by scottschiller** [comment]
Thanks for confirming; glad to get this one sorted.

**Comment by whoisterencelee** [comment]
Confirm working on desktop firefox as well, nice
