### ISSUE TITLE
Request for two command options for mobile

### ISSUE THREAD

**Issue by artfoundry** [scottschiller/ArmorAlley#9]
Need to have a command for mobile to flip the direction of the chopper, so that you can fly backward (like maybe double tap or tap with second finger).  Also an option for mobile to change the movement velocity (to make flying slower and doing tricky agility maneuvers easier).

**Comment by scottschiller** [comment]
Thanks for the thoughts. I think a double-tap could work regarding direction, if done in "empty space" and not on a button etc. I can look at slowing down the "rate" at which the helicopter chases the pointer, per se - perhaps make that an option in preferences.

**Comment by scottschiller** [comment]
Update! "Auto-flip" is now a preference in settings.

When auto-flip is _off_:
* Using a mouse: you can click (on desktop) to flip the helicopter manually.
* On a touchscreen, double-tap to flip manually.

Auto-flip can also be toggled in-game, in addition to using the options panel.
* Using a keyboard: the `F` key toggles, like the original game.
* On a touchscreen, triple-tap to toggle. (I tried to restrict this to three quick taps within a 32px square, and can adjust if it turns out to be finicky.)

**Comment by artfoundry** [comment]
Having the option to turn off auto flip makes a huge difference on mobile!
Turning down game speed even just 20% also really helps with helicopter control on mobile.  Did you intend to have it defaulted to 115%?

**Comment by scottschiller** [comment]
Thanks for trying out the latest.

I've gotten used to the prior auto-flip behaviour on mobile and knowing that I can "turn and fire" pretty reliably, but I'll try it with the feature off and see how it works. I think the double and triple-tap are working OK, but let me know if you find them to be buggy or inconsistent.

I made a few changes to the game speed code in development, and may have messed up local storage along the way. The game speed _should_ default to 100% - opening a new / incognito browser should confirm that. With the range being 25% to 200%, the default 100% position is not visually centered on the slider UI. I don't love the look, but each "notch" is an increment of 5%. I didn't want to go down to 0%, but maybe I illustrate it and have a cut-off at 5% or something. ;)

**Comment by scottschiller** [comment]
Setting a default speed of 80% or similar on mobile might be wise. The game does feel a bit fast-paced and frantic when using touch controls.

**Comment by artfoundry** [comment]
Ok I do see 100% default with incognito. Weird - I did actually see the number 115 before, but maybe I hit the slider accidentally without realizing it or something.

**Comment by scottschiller** [comment]
I forgot to link and mention - I've set the game default speed to [80% for mobile/touch](cece24fc4729630861d63727797532a1db4e80d0), I think your suggestion was spot on. The game feels nicely paced on smaller screens at that speed.

I'm marking this resolved, thanks again for the great feedback.
